application: mf-game-api-v1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# The endpoints handler must be mapped to /_ah/spi.
# Apps send requests to /_ah/api, but the endpoints service handles mapping
# those requests to /_ah/spi.


- url: /_ah/spi/.*
  script: main.api

- url: /crons/send_reminder
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: latest

